# Generated by Django 3.2.12 on 2022-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetups_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='location',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
