# Generated by Django 3.2.12 on 2022-02-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetups_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='image',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
