# Generated by Django 3.2.12 on 2022-02-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20220224_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
