# Generated by Django 3.2.12 on 2022-02-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_auto_20220224_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetups',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participant'),
        ),
    ]
