# Generated by Django 3.2.12 on 2022-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_auto_20220224_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='date',
            field=models.DateField(default='2021-04-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetups',
            name='organizer_email',
            field=models.EmailField(default='njeanluc828@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
